#!/bin/bash
./train_AttH_UKC_32.sh
./train_AttH_UKC_500.sh
./train_ComplEx_UKC_32.sh
./train_ComplEx_UKC_500.sh
./train_RefH_UKC_32.sh
./train_RefH_UKC_500.sh
./train_RotE_UKC_32.sh
./train_RotE_UKC_500.sh
./train_RotH_UKC_32.sh
./train_RotH_UKC_500.sh